/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { writeRecords } from "../../funcs/writeRecords.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.WriteRecordsRequest$inboundSchema,
};

export const tool$writeRecords: ToolDefinition<typeof args> = {
  name: "write-records",
  description: `Write records`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await writeRecords(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
