/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Write } from "./write.js";

export class SDKNodeWrite extends ClientSDK {
  private _write?: Write;
  get write(): Write {
    return (this._write ??= new Write(this._options));
  }
}
