/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { RecordsAcceptEnum, writeRecords } from "../funcs/writeRecords.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { RecordsAcceptEnum } from "../funcs/writeRecords.js";

export class Write extends ClientSDK {
  /**
   * Write records
   */
  async records(
    request: operations.WriteRecordsRequest,
    options?: RequestOptions & { acceptHeaderOverride?: RecordsAcceptEnum },
  ): Promise<operations.WriteRecordsResponse> {
    return unwrapAsync(writeRecords(
      this,
      request,
      options,
    ));
  }
}
